meilisearch:
  url: '%env(MEILISEARCH_URL)%'          # URL of the Meilisearch server (mandatory)
  api_key: '%env(MEILISEARCH_API_KEY)%'  # API key to access the Meilisearch server (mandatory)
  doctrineSubscribedEvents: ['postPersist', 'postUpdate', 'preRemove']
  indices:
    - name: offers
      class: App\Entity\Offers
      enable_serializer_groups: true