twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        img_enterprises: '/images/enterprises/'
        img_students: '/images/students/'

when@test:
    twig:
        strict_variables: true
