twig:
    default_path: '%kernel.project_dir%/templates'
#    form_themes:
#        - form_themes/tailwind.html.twig
    globals:
        img_enterprises: '/images/enterprises/'

when@test:
    twig:
        strict_variables: true
