version: '3'
services:
  app:
    image: baptistechab/projet-alternance:latest
    ports:
      - "8080:80"
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projet_dawin1
    ports:
      - "6033:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: