version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: changeMe
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    image: baptistechab/projet-alternance:latest
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: mysql://symfony:changeMe@db:3306/app


volumes:
  db-data: